name: Build and Push limecommerce service

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        
    - name: Cache
      uses: actions/cache@v3.3.0
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2 
        
    - name: Clean
      run: mvn -B clean -DskipTests -DBUILD_NUMBER=${{ github.run_number }}

    - name: Build
      run: mvn -B package -DskipTests -DBUILD_NUMBER=${{ github.run_number }}

    - name: Push to Artifact Registry
      run: |
        #? set the password to push to artifact registry
        export MAVEN_ARTIFACT_CREDENTIALS=${{ secrets.MAVEN_ARTIFACT_CREDENTIALS }}
        mvn -s settings.xml -X -B deploy -DskipTests -DBUILD_NUMBER=${{ github.run_number }} -e